import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#424753",
        "on-primary-fixed": "#161e00",
        "tertiary-fixed-dim": "#adc6ff",
        "inverse-on-surface": "#2f3034",
        "surface-container-highest": "#333538",
        "surface-tint": "#abd600",
        "border-subtle": "#283040",
        "on-tertiary-fixed": "#001a42",
        "secondary-fixed": "#dee2f1",
        "outline": "#8e9379",
        "on-primary-container": "#556d00",
        "secondary": "#c2c6d5",
        "badge-fact-text": "#10B981",
        "on-surface": "#e2e2e6",
        "text-dim": "#6B7280",
        "background": "#111317",
        "on-primary": "#283500",
        "error": "#ffb4ab",
        "badge-fact-bg": "#064E3B",
        "secondary-container": "#444955",
        "surface-bright": "#37393d",
        "primary": "#ffffff",
        "badge-gap-risk": "#EF4444",
        "secondary-fixed-dim": "#c2c6d5",
        "badge-inference": "#F59E0B",
        "on-surface-variant": "#c4c9ac",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary-fixed": "#171c26",
        "outline-variant": "#444933",
        "error-container": "#93000a",
        "primary-container": "#c3f400",
        "on-tertiary": "#002e6a",
        "on-error-container": "#ffdad6",
        "badge-claim-text": "#3B82F6",
        "accent-acid": "#CCFF00",
        "primary-fixed": "#c3f400",
        "surface-container": "#1e2023",
        "surface": "#111317",
        "text-ivory": "#F9FAFB",
        "surface-card": "#181C24",
        "surface-dim": "#111317",
        "badge-claim-bg": "#1E3A8A",
        "tertiary": "#ffffff",
        "surface-variant": "#333538",
        "surface-container-lowest": "#0c0e11",
        "on-tertiary-fixed-variant": "#004395",
        "surface-elevated": "#1E232E",
        "badge-reporting": "#8B5CF6",
        "tertiary-container": "#d8e2ff",
        "on-tertiary-container": "#0060ce",
        "surface-container-high": "#282a2d",
        "on-error": "#690005",
        "on-secondary": "#2b303c",
        "text-muted": "#9CA3AF",
        "primary-fixed-dim": "#abd600",
        "on-primary-fixed-variant": "#3c4d00",
        "surface-container-low": "#1a1c1f",
        "on-background": "#e2e2e6",
        "inverse-primary": "#506600",
        "canvas-base": "#0D0F12",
        "on-secondary-container": "#b4b8c7",
        "inverse-surface": "#e2e2e6"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        margin: "1.5rem",
        "space-lg": "1.5rem",
        gutter: "1.25rem"
      },
      fontFamily: {
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "body-default": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "display-hero-mobile": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "display-hero": ["IBM Plex Sans", "sans-serif"],
        "body-dense": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "body-lead": ["IBM Plex Sans", "sans-serif"],
        "caption-code": ["IBM Plex Sans", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-default": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "34px", fontWeight: "600" }],
        "display-hero-mobile": ["26px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "38px", fontWeight: "700" }],
        "display-hero": ["32px", { lineHeight: "44px", fontWeight: "700" }],
        "body-dense": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "30px", fontWeight: "600" }],
        "body-lead": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "caption-code": ["11px", { lineHeight: "14px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
};
export default config;
